// Mocks generated by Mockito 5.4.6 from annotations
// in live_translator/test/src/home/presentation/home_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:typed_data' as _i12;

import 'package:flutter_gemini/flutter_gemini.dart' as _i7;
import 'package:flutter_gemini/src/models/candidates/candidates.dart' as _i8;
import 'package:flutter_gemini/src/models/content/content.dart' as _i9;
import 'package:flutter_gemini/src/models/gemini_model/gemini_model.dart'
    as _i2;
import 'package:flutter_gemini/src/models/gemini_safety/gemini_safety.dart'
    as _i10;
import 'package:flutter_gemini/src/models/generation_config/generation_config.dart'
    as _i11;
import 'package:flutter_gemini/src/models/part/part.dart' as _i13;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:speech_to_text/speech_to_text.dart' as _i3;
import 'package:speech_to_text_platform_interface/speech_to_text_platform_interface.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeGeminiModel_0 extends _i1.SmartFake implements _i2.GeminiModel {
  _FakeGeminiModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SpeechToText].
///
/// See the documentation for Mockito's code generation for more information.
class MockSpeechToText extends _i1.Mock implements _i3.SpeechToText {
  MockSpeechToText() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get hasRecognized => (super.noSuchMethod(
        Invocation.getter(#hasRecognized),
        returnValue: false,
      ) as bool);

  @override
  String get lastRecognizedWords => (super.noSuchMethod(
        Invocation.getter(#lastRecognizedWords),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#lastRecognizedWords),
        ),
      ) as String);

  @override
  String get lastStatus => (super.noSuchMethod(
        Invocation.getter(#lastStatus),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#lastStatus),
        ),
      ) as String);

  @override
  double get lastSoundLevel => (super.noSuchMethod(
        Invocation.getter(#lastSoundLevel),
        returnValue: 0.0,
      ) as double);

  @override
  bool get isAvailable => (super.noSuchMethod(
        Invocation.getter(#isAvailable),
        returnValue: false,
      ) as bool);

  @override
  bool get isListening => (super.noSuchMethod(
        Invocation.getter(#isListening),
        returnValue: false,
      ) as bool);

  @override
  bool get isNotListening => (super.noSuchMethod(
        Invocation.getter(#isNotListening),
        returnValue: false,
      ) as bool);

  @override
  bool get hasError => (super.noSuchMethod(
        Invocation.getter(#hasError),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<bool> get hasPermission => (super.noSuchMethod(
        Invocation.getter(#hasPermission),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  set errorListener(_i3.SpeechErrorListener? value) => super.noSuchMethod(
        Invocation.setter(
          #errorListener,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set statusListener(_i3.SpeechStatusListener? value) => super.noSuchMethod(
        Invocation.setter(
          #statusListener,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<bool> initialize({
    _i3.SpeechErrorListener? onError,
    _i3.SpeechStatusListener? onStatus,
    dynamic debugLogging = false,
    Duration? finalTimeout = const Duration(milliseconds: 2000),
    List<_i6.SpeechConfigOption>? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
          {
            #onError: onError,
            #onStatus: onStatus,
            #debugLogging: debugLogging,
            #finalTimeout: finalTimeout,
            #options: options,
          },
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> stop() => (super.noSuchMethod(
        Invocation.method(
          #stop,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> cancel() => (super.noSuchMethod(
        Invocation.method(
          #cancel,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<dynamic> listen({
    _i3.SpeechResultListener? onResult,
    Duration? listenFor,
    Duration? pauseFor,
    String? localeId,
    _i3.SpeechSoundLevelChange? onSoundLevelChange,
    dynamic cancelOnError = false,
    dynamic partialResults = true,
    dynamic onDevice = false,
    _i6.ListenMode? listenMode = _i6.ListenMode.confirmation,
    dynamic sampleRate = 0,
    _i6.SpeechListenOptions? listenOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listen,
          [],
          {
            #onResult: onResult,
            #listenFor: listenFor,
            #pauseFor: pauseFor,
            #localeId: localeId,
            #onSoundLevelChange: onSoundLevelChange,
            #cancelOnError: cancelOnError,
            #partialResults: partialResults,
            #onDevice: onDevice,
            #listenMode: listenMode,
            #sampleRate: sampleRate,
            #listenOptions: listenOptions,
          },
        ),
        returnValue: _i5.Future<dynamic>.value(),
      ) as _i5.Future<dynamic>);

  @override
  void changePauseFor(Duration? pauseFor) => super.noSuchMethod(
        Invocation.method(
          #changePauseFor,
          [pauseFor],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<List<_i3.LocaleName>> locales() => (super.noSuchMethod(
        Invocation.method(
          #locales,
          [],
        ),
        returnValue: _i5.Future<List<_i3.LocaleName>>.value(<_i3.LocaleName>[]),
      ) as _i5.Future<List<_i3.LocaleName>>);

  @override
  _i5.Future<_i3.LocaleName?> systemLocale() => (super.noSuchMethod(
        Invocation.method(
          #systemLocale,
          [],
        ),
        returnValue: _i5.Future<_i3.LocaleName?>.value(),
      ) as _i5.Future<_i3.LocaleName?>);
}

/// A class which mocks [Gemini].
///
/// See the documentation for Mockito's code generation for more information.
class MockGemini extends _i1.Mock implements _i7.Gemini {
  MockGemini() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get disableAutoUpdateModelName => (super.noSuchMethod(
        Invocation.getter(#disableAutoUpdateModelName),
        returnValue: false,
      ) as bool);

  @override
  set typeProvider(dynamic value) => super.noSuchMethod(
        Invocation.setter(
          #typeProvider,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set disableAutoUpdateModelName(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #disableAutoUpdateModelName,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<_i8.Candidates?> chat(
    List<_i9.Content>? chats, {
    String? modelName,
    List<_i10.SafetySetting>? safetySettings,
    _i11.GenerationConfig? generationConfig,
    String? systemPrompt,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #chat,
          [chats],
          {
            #modelName: modelName,
            #safetySettings: safetySettings,
            #generationConfig: generationConfig,
            #systemPrompt: systemPrompt,
          },
        ),
        returnValue: _i5.Future<_i8.Candidates?>.value(),
      ) as _i5.Future<_i8.Candidates?>);

  @override
  _i5.Stream<_i8.Candidates> streamChat(
    List<_i9.Content>? chats, {
    String? modelName,
    List<_i10.SafetySetting>? safetySettings,
    _i11.GenerationConfig? generationConfig,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #streamChat,
          [chats],
          {
            #modelName: modelName,
            #safetySettings: safetySettings,
            #generationConfig: generationConfig,
          },
        ),
        returnValue: _i5.Stream<_i8.Candidates>.empty(),
      ) as _i5.Stream<_i8.Candidates>);

  @override
  _i5.Future<int?> countTokens(
    String? text, {
    String? modelName,
    List<_i10.SafetySetting>? safetySettings,
    _i11.GenerationConfig? generationConfig,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #countTokens,
          [text],
          {
            #modelName: modelName,
            #safetySettings: safetySettings,
            #generationConfig: generationConfig,
          },
        ),
        returnValue: _i5.Future<int?>.value(),
      ) as _i5.Future<int?>);

  @override
  _i5.Future<_i2.GeminiModel> info({required String? model}) =>
      (super.noSuchMethod(
        Invocation.method(
          #info,
          [],
          {#model: model},
        ),
        returnValue: _i5.Future<_i2.GeminiModel>.value(_FakeGeminiModel_0(
          this,
          Invocation.method(
            #info,
            [],
            {#model: model},
          ),
        )),
      ) as _i5.Future<_i2.GeminiModel>);

  @override
  _i5.Future<List<_i2.GeminiModel>> listModels() => (super.noSuchMethod(
        Invocation.method(
          #listModels,
          [],
        ),
        returnValue:
            _i5.Future<List<_i2.GeminiModel>>.value(<_i2.GeminiModel>[]),
      ) as _i5.Future<List<_i2.GeminiModel>>);

  @override
  _i5.Stream<_i8.Candidates> streamGenerateContent(
    String? text, {
    List<_i12.Uint8List>? images,
    String? modelName,
    List<_i10.SafetySetting>? safetySettings,
    _i11.GenerationConfig? generationConfig,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #streamGenerateContent,
          [text],
          {
            #images: images,
            #modelName: modelName,
            #safetySettings: safetySettings,
            #generationConfig: generationConfig,
          },
        ),
        returnValue: _i5.Stream<_i8.Candidates>.empty(),
      ) as _i5.Stream<_i8.Candidates>);

  @override
  _i5.Future<_i8.Candidates?> textAndImage({
    required String? text,
    required List<_i12.Uint8List>? images,
    String? modelName,
    List<_i10.SafetySetting>? safetySettings,
    _i11.GenerationConfig? generationConfig,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #textAndImage,
          [],
          {
            #text: text,
            #images: images,
            #modelName: modelName,
            #safetySettings: safetySettings,
            #generationConfig: generationConfig,
          },
        ),
        returnValue: _i5.Future<_i8.Candidates?>.value(),
      ) as _i5.Future<_i8.Candidates?>);

  @override
  _i5.Future<_i8.Candidates?> text(
    String? text, {
    String? modelName,
    List<_i10.SafetySetting>? safetySettings,
    _i11.GenerationConfig? generationConfig,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #text,
          [text],
          {
            #modelName: modelName,
            #safetySettings: safetySettings,
            #generationConfig: generationConfig,
          },
        ),
        returnValue: _i5.Future<_i8.Candidates?>.value(),
      ) as _i5.Future<_i8.Candidates?>);

  @override
  _i5.Future<List<List<num>?>?> batchEmbedContents(
    List<String>? texts, {
    String? modelName,
    List<_i10.SafetySetting>? safetySettings,
    _i11.GenerationConfig? generationConfig,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #batchEmbedContents,
          [texts],
          {
            #modelName: modelName,
            #safetySettings: safetySettings,
            #generationConfig: generationConfig,
          },
        ),
        returnValue: _i5.Future<List<List<num>?>?>.value(),
      ) as _i5.Future<List<List<num>?>?>);

  @override
  _i5.Future<List<num>?> embedContent(
    String? text, {
    String? modelName,
    List<_i10.SafetySetting>? safetySettings,
    _i11.GenerationConfig? generationConfig,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #embedContent,
          [text],
          {
            #modelName: modelName,
            #safetySettings: safetySettings,
            #generationConfig: generationConfig,
          },
        ),
        returnValue: _i5.Future<List<num>?>.value(),
      ) as _i5.Future<List<num>?>);

  @override
  _i5.Future<void> cancelRequest() => (super.noSuchMethod(
        Invocation.method(
          #cancelRequest,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i8.Candidates?> prompt({
    required List<_i13.Part>? parts,
    String? model,
    List<_i10.SafetySetting>? safetySettings,
    _i11.GenerationConfig? generationConfig,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #prompt,
          [],
          {
            #parts: parts,
            #model: model,
            #safetySettings: safetySettings,
            #generationConfig: generationConfig,
          },
        ),
        returnValue: _i5.Future<_i8.Candidates?>.value(),
      ) as _i5.Future<_i8.Candidates?>);

  @override
  _i5.Stream<_i8.Candidates?> promptStream({
    required List<_i13.Part>? parts,
    String? model,
    List<_i10.SafetySetting>? safetySettings,
    _i11.GenerationConfig? generationConfig,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #promptStream,
          [],
          {
            #parts: parts,
            #model: model,
            #safetySettings: safetySettings,
            #generationConfig: generationConfig,
          },
        ),
        returnValue: _i5.Stream<_i8.Candidates?>.empty(),
      ) as _i5.Stream<_i8.Candidates?>);
}
